#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in

   start)
     stat_busy "Starting radeon_gc_off..."
     echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
     echo "OFF"  > /sys/kernel/debug/vgaswitcheroo/switch
     add_daemon radeon_gc_off
     stat_done
   ;;

   stop)
     stat_busy "Stopping radeon_gc_off..."
     echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
     echo "DDIS" > /sys/kernel/debug/vgaswitcheroo/switch
     rm_daemon radeon_gc_off
     stat_done
   ;;

   restart)
     $0 stop
     sleep 1
     $0 start
   ;;

   *)
cat /sys/kernel/debug/vgaswitcheroo/switch
     echo "usage: $0 {start|stop|restart}"
esac
