# qwerty-layout
keycode  16 = q
keycode  17 = w
keycode  18 = e
keycode  19 = r
keycode  20 = t
keycode  22 = y
keycode  23 = u
keycode  24 = i
keycode  25 = o
keycode  26 = p
#
keycode  30 = a
keycode  31 = s
keycode  32 = d
keycode  33 = f
keycode  34 = g
keycode  36 = h
keycode  37 = j
keycode  38 = k
keycode  39 = l
#
keycode  44 = z
keycode  45 = x
keycode  46 = c
keycode  47 = v
keycode  48 = b
keycode  50 = n
keycode  51 = m
#
include "compose"
