#!/bin/sh

FIFO="/tmp/dvtm-status.$$"
LOG="/tmp/dvtm-status.$$.log"

[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
	laptop-status 2>> "$LOG"
	sleep 60
done > "$FIFO" &

STATUS_PID=$!
dvtm -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
